### ISSUE TITLE
Make the state of graph (locked / unlocked) more obvious for new users

### ISSUE THREAD

**Issue by kavon** [mcnuttandrew/forum-explorer#47]
I suggest using emojis or something. Currently you have to look at bottom left of graph and read the text to know when it's locked to a given comment chain.

I eventually figured out that the graph seems to make the comment chain bolder when its locked, but it took some time to understand that.

**Comment by mcnuttandrew** [comment]
I think it's more obvious now???? @kavon what do you think?

**Comment by kavon** [comment]
yes, moving the text to the top right makes it a lot easier to see.
