### ISSUE TITLE
Graph doesn't shrink enough and ends up vertically clipped

### ISSUE THREAD

**Issue by jolmg** [mcnuttandrew/forum-explorer#68]
Browser: Firefox 66.0.5
OS: Archlinux last updated on the 8th of May.

This is my browser window:

![forum-explorer-vertical-clipping](https://user-images.githubusercontent.com/17855790/57732525-23b57080-7652-11e9-82b2-d1bade472b45.png)

**Comment by jolmg** [comment]
Original YC comment that prompted this:
https://news.ycombinator.com/item?id=19913203

I know I said it also happens to me, but on re-reading JohnFen's comment, I think he's referring to something different. When your browser window is vertically small enough, you can't read the "Some Interesting Examples part or even the text above it:

![forum-explorer-vertical-clipping-2](https://user-images.githubusercontent.com/17855790/57733186-c4f0f680-7653-11e9-9405-fc6624901e52.png)

**Comment by mcnuttandrew** [comment]
Okay! I believe this problem to be addressed so I'm going to mark it as resolved. if it isn't i'd be happy to reopen and address it right

**Comment by jolmg** [comment]
Yup. This is done. I can't get the graphs to clip.
