### ISSUE TITLE
Not all content that is vertically clipped can be accessed by scrolling.

### ISSUE THREAD

**Issue by jolmg** [mcnuttandrew/forum-explorer#69]
Original YC comment that prompted this:
https://news.ycombinator.com/item?id=19913203

I know I said it also happens to me, but on re-reading JohnFen's comment, I think he's referring to something different. When your browser window is vertically small enough, you can't read the "Some Interesting Examples" part or even the text above it:

![forum-explorer-vertical-clipping-2](https://user-images.githubusercontent.com/17855790/57733322-1f8a5280-7654-11e9-94da-f5db93e8c468.png)

**Comment by mcnuttandrew** [comment]
I think this one is also addressed! Let me know if not

**Comment by jolmg** [comment]
Just to be clear, if you consider this done yourself, that's fine. I'm just trying to help.

That said, I can't read the second paragraph:

![forum-explorer-issue-69-cant-read-second-paragraph](https://user-images.githubusercontent.com/17855790/57786498-6de93100-76e8-11e9-9ddb-06980cddc3fa.png)

**Comment by jolmg** [comment]
What's wrong with making the whole page scrollable?

**Comment by jolmg** [comment]
Then again, someone with a window that small or that bad a resolution would still not be able to use the page with the graph that well, so I guess there's not *that* much to gain in making this particular page usable at such a window size. The fix you did is probably fine then.

Another thing to consider might be the accessibility of the posts. At a window size like this:

![forum-explorer-issue-69-accessibility-of-posts](https://user-images.githubusercontent.com/17855790/57787952-22845200-76eb-11e9-88fb-6dbacc38cc15.png)

The posts can hardly be accessed. It's like the UI considers the introductory paragraphs as more important than the posts themselves. Also, to access the posts on the right, you have to trick the browser into horizontal scrolling by selecting the text towards the right.

I'm just offering what I can in critique. You have to decide what problems are worth pursuing. I'm probably not going to use this much if at all, but that's because the visualizations, while interesting, aren't really *that* useful to me.

**Comment by mcnuttandrew** [comment]
I appreciate your thinking and feedback! The main target of this work is to provide an MVP for this concept (especially the forested tree view stuff), and not to be a full free standing product.

>I'm just offering what I can in critique. You have to decide what problems are worth pursuing. I'm probably not going to use this much if at all, but that's because the visualizations, while interesting, aren't really that useful to me.

That's super reasonable! This is a pretty experimental interface, and not all experiments need to be perfect. I'm just glad you liked it enough to give such detailed feedback.

**Comment by jolmg** [comment]
I just remembered #71. More important than the points I raised above, a benefit of making the whole page scrollable is that it would've fixed #71 as well. One still can't access the "Some Interesting Examples" section on Firefox on Android.
